#pragma once
enum Event
{
	CURSOR_MOVED = 0,
	RIGHT_MOUSE_BUTTON_PRESSED = 1,
	LEFT_MOUSE_BUTTON_PRESSED = 2,
	C_KEY_PRESSED = 3,
	WINDOW_RESIZED = 4,
	MOUSE_SCROLL = 5,
	FOV_CHANGED = 6,
	CAMERA_UPDATE = 7,
	LIGHT_UPDATE = 8,
	LEFT_CTRL_PRESSED = 9,
};

