extern float sphere[];
extern float bushes[];
extern float tree[];
extern float gift[];
extern float plain[];
extern float suziFlat[];
extern float suziSmooth[];
extern float triangle[];
extern float skycube[];